# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.1.0'

# Vulnerable packages for testing vulnerability scanning
gem 'rack', '2.0.6'           # CVE-2020-8161, CVE-2020-8184, CVE-2022-30122, CVE-2022-30123
gem 'nokogiri', '1.10.0'      # Multiple CVEs: CVE-2019-5477, CVE-2020-26247
gem 'rails', '5.2.0'          # Multiple CVEs including CVE-2019-5418, CVE-2019-5419
gem 'activerecord', '5.2.0'   # CVE-2021-22880, CVE-2021-22904
gem 'actionview', '5.2.0'     # CVE-2019-5418, CVE-2020-5267
gem 'puma', '3.12.0'          # CVE-2019-16770, CVE-2020-5247, CVE-2021-29509
gem 'devise', '4.4.0'         # CVE-2019-5421
gem 'json', '1.8.6'           # CVE-2020-10663

# Additional vulnerable gems
gem 'loofah', '2.2.0'         # CVE-2018-16468
gem 'sprockets', '3.7.1'      # CVE-2018-3760
gem 'websocket-extensions', '0.1.3'  # CVE-2020-7663

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.57'
end
