# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.1.0'

gem 'httparty', '~> 0.21'
gem 'json', '~> 2.6'
gem 'rack-cors', '~> 2.0'
gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib', '~> 3.0'

# License testing - various license types
gem 'rails', '~> 7.1'
gem 'pg', '~> 1.5'
gem 'redis', '~> 5.0'
gem 'sidekiq', '~> 7.2'
gem 'puma', '~> 6.4'
gem 'nokogiri', '~> 1.15'
gem 'faraday', '~> 2.7'
gem 'jwt', '~> 2.7'

group :development, :test do
  gem 'rack-test', '~> 2.1'
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.57'
  gem 'rubocop-rspec', '~> 2.24'
  gem 'factory_bot', '~> 6.4'
  gem 'faker', '~> 3.2'
end
